spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/myspringtest
    username: sa
    pasword:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  resources:
     static-locations: classpath:/static/

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 9080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace