spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    pasword:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  resources:
     static-locations: classpath:/static/

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # 이렇게 해놓으면 collection의 데이터를 in 쿼리로 가져와버림 (여기 적은 숫자만큼..!)

server:
  port: 9080

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace