spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    pasword:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #s show_sql: true
        format_sql: true
server:
  port: 9080

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace